package com.xwkj.ygjces.Mapper_oracle.auto;

import com.xwkj.ygjces.model.JcHtContract;
import org.springframework.stereotype.Repository;

@Repository
public interface JcHtContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JC_HT_CONTRACT
     *
     * @mbggenerated Fri Jul 26 15:55:36 CST 2019
     */
    int deleteByPrimaryKey(String contractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JC_HT_CONTRACT
     *
     * @mbggenerated Fri Jul 26 15:55:36 CST 2019
     */
    int insert(JcHtContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JC_HT_CONTRACT
     *
     * @mbggenerated Fri Jul 26 15:55:36 CST 2019
     */
    int insertSelective(JcHtContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JC_HT_CONTRACT
     *
     * @mbggenerated Fri Jul 26 15:55:36 CST 2019
     */
    JcHtContract selectByPrimaryKey(String contractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JC_HT_CONTRACT
     *
     * @mbggenerated Fri Jul 26 15:55:36 CST 2019
     */
    int updateByPrimaryKeySelective(JcHtContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JC_HT_CONTRACT
     *
     * @mbggenerated Fri Jul 26 15:55:36 CST 2019
     */
    int updateByPrimaryKey(JcHtContract record);
}