package com.xwkj.ygjces.model;

import java.util.Date;

public class ApproverLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_task_approver_log.pid
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_task_approver_log.taskId
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    private Long taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_task_approver_log.create_date
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_task_approver_log.userId
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_task_approver_log.reason
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_task_approver_log.filePath
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_task_approver_log.status
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    private Integer status;

    private String userName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_task_approver_log.pid
     *
     * @return the value of tbl_task_approver_log.pid
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_task_approver_log.pid
     *
     * @param pid the value for tbl_task_approver_log.pid
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_task_approver_log.taskId
     *
     * @return the value of tbl_task_approver_log.taskId
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public Long getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_task_approver_log.taskId
     *
     * @param taskid the value for tbl_task_approver_log.taskId
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public void setTaskid(Long taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_task_approver_log.create_date
     *
     * @return the value of tbl_task_approver_log.create_date
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_task_approver_log.create_date
     *
     * @param createDate the value for tbl_task_approver_log.create_date
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_task_approver_log.userId
     *
     * @return the value of tbl_task_approver_log.userId
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_task_approver_log.userId
     *
     * @param userid the value for tbl_task_approver_log.userId
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_task_approver_log.reason
     *
     * @return the value of tbl_task_approver_log.reason
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_task_approver_log.reason
     *
     * @param reason the value for tbl_task_approver_log.reason
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_task_approver_log.filePath
     *
     * @return the value of tbl_task_approver_log.filePath
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_task_approver_log.filePath
     *
     * @param filepath the value for tbl_task_approver_log.filePath
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_task_approver_log.status
     *
     * @return the value of tbl_task_approver_log.status
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_task_approver_log.status
     *
     * @param status the value for tbl_task_approver_log.status
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}