package com.xwkj.ygjces.model;

import java.util.Date;

public class NoticeModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_xm_notice.pid
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_xm_notice.content
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_xm_notice.xm_id
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    private String xmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_xm_notice.create_date
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_xm_notice.send_date
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    private Date sendDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_xm_notice.is_render
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    private Integer isRender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_xm_notice.render_date
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    private Date renderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_xm_notice.category
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_xm_notice.userId
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_xm_notice.stage
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    private Integer stage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_xm_notice.pid
     *
     * @return the value of tbl_gb_xm_notice.pid
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_xm_notice.pid
     *
     * @param pid the value for tbl_gb_xm_notice.pid
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_xm_notice.content
     *
     * @return the value of tbl_gb_xm_notice.content
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_xm_notice.content
     *
     * @param content the value for tbl_gb_xm_notice.content
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_xm_notice.xm_id
     *
     * @return the value of tbl_gb_xm_notice.xm_id
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public String getXmId() {
        return xmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_xm_notice.xm_id
     *
     * @param xmId the value for tbl_gb_xm_notice.xm_id
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public void setXmId(String xmId) {
        this.xmId = xmId == null ? null : xmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_xm_notice.create_date
     *
     * @return the value of tbl_gb_xm_notice.create_date
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_xm_notice.create_date
     *
     * @param createDate the value for tbl_gb_xm_notice.create_date
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_xm_notice.send_date
     *
     * @return the value of tbl_gb_xm_notice.send_date
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public Date getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_xm_notice.send_date
     *
     * @param sendDate the value for tbl_gb_xm_notice.send_date
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_xm_notice.is_render
     *
     * @return the value of tbl_gb_xm_notice.is_render
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public Integer getIsRender() {
        return isRender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_xm_notice.is_render
     *
     * @param isRender the value for tbl_gb_xm_notice.is_render
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public void setIsRender(Integer isRender) {
        this.isRender = isRender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_xm_notice.render_date
     *
     * @return the value of tbl_gb_xm_notice.render_date
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public Date getRenderDate() {
        return renderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_xm_notice.render_date
     *
     * @param renderDate the value for tbl_gb_xm_notice.render_date
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public void setRenderDate(Date renderDate) {
        this.renderDate = renderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_xm_notice.category
     *
     * @return the value of tbl_gb_xm_notice.category
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_xm_notice.category
     *
     * @param category the value for tbl_gb_xm_notice.category
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_xm_notice.userId
     *
     * @return the value of tbl_gb_xm_notice.userId
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_xm_notice.userId
     *
     * @param userid the value for tbl_gb_xm_notice.userId
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_xm_notice.stage
     *
     * @return the value of tbl_gb_xm_notice.stage
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public Integer getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_xm_notice.stage
     *
     * @param stage the value for tbl_gb_xm_notice.stage
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    public void setStage(Integer stage) {
        this.stage = stage;
    }
}