package com.xwkj.ygjces.model;

public class OrganizationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_organization_info.id
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_organization_info.name
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_organization_info.p_id
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    private Long pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_organization_info.isEnablez
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    private Integer isenablez;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_organization_info.id
     *
     * @return the value of tbl_gb_organization_info.id
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_organization_info.id
     *
     * @param id the value for tbl_gb_organization_info.id
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_organization_info.name
     *
     * @return the value of tbl_gb_organization_info.name
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_organization_info.name
     *
     * @param name the value for tbl_gb_organization_info.name
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_organization_info.p_id
     *
     * @return the value of tbl_gb_organization_info.p_id
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    public Long getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_organization_info.p_id
     *
     * @param pId the value for tbl_gb_organization_info.p_id
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    public void setpId(Long pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_organization_info.isEnablez
     *
     * @return the value of tbl_gb_organization_info.isEnablez
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    public Integer getIsenablez() {
        return isenablez;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_organization_info.isEnablez
     *
     * @param isenablez the value for tbl_gb_organization_info.isEnablez
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    public void setIsenablez(Integer isenablez) {
        this.isenablez = isenablez;
    }
}