package com.xwkj.ygjces.model;

import java.util.Date;

public class TaskOverTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.id
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.task_id
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.task_des
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private String taskDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.initiator
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Long initiator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.end_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.deptId
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private String deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.source
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.level
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Long level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.note
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.create_time
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_overtime.is_finish
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Integer isFinish;



    private String deptName;

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.id
     *
     * @return the value of tbl_gb_task_overtime.id
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.id
     *
     * @param id the value for tbl_gb_task_overtime.id
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.task_id
     *
     * @return the value of tbl_gb_task_overtime.task_id
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.task_id
     *
     * @param taskId the value for tbl_gb_task_overtime.task_id
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.task_des
     *
     * @return the value of tbl_gb_task_overtime.task_des
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public String getTaskDes() {
        return taskDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.task_des
     *
     * @param taskDes the value for tbl_gb_task_overtime.task_des
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setTaskDes(String taskDes) {
        this.taskDes = taskDes == null ? null : taskDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.initiator
     *
     * @return the value of tbl_gb_task_overtime.initiator
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Long getInitiator() {
        return initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.initiator
     *
     * @param initiator the value for tbl_gb_task_overtime.initiator
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setInitiator(Long initiator) {
        this.initiator = initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.end_date
     *
     * @return the value of tbl_gb_task_overtime.end_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.end_date
     *
     * @param endDate the value for tbl_gb_task_overtime.end_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.deptId
     *
     * @return the value of tbl_gb_task_overtime.deptId
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.deptId
     *
     * @param deptid the value for tbl_gb_task_overtime.deptId
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.source
     *
     * @return the value of tbl_gb_task_overtime.source
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.source
     *
     * @param source the value for tbl_gb_task_overtime.source
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.level
     *
     * @return the value of tbl_gb_task_overtime.level
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Long getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.level
     *
     * @param level the value for tbl_gb_task_overtime.level
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setLevel(Long level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.note
     *
     * @return the value of tbl_gb_task_overtime.note
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.note
     *
     * @param note the value for tbl_gb_task_overtime.note
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.create_time
     *
     * @return the value of tbl_gb_task_overtime.create_time
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.create_time
     *
     * @param createTime the value for tbl_gb_task_overtime.create_time
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_overtime.is_finish
     *
     * @return the value of tbl_gb_task_overtime.is_finish
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Integer getIsFinish() {
        return isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_overtime.is_finish
     *
     * @param isFinish the value for tbl_gb_task_overtime.is_finish
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setIsFinish(Integer isFinish) {
        this.isFinish = isFinish;
    }
}