package com.xwkj.ygjces.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class TaskInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.pid
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.task_des
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private String taskDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.initiator
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Long initiator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.end_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.actual_end_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date actualEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.deptId
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private String deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.status
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.source
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.level
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Long level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.note
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.first_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Integer firstDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.over_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Integer overDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.create_time
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_gb_task_info.p_id
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    private Long pId;



    private String deptName;

    private String subDeptName;

    private String levelName;

    private Date nowTime;

    private String userName;

    private Integer isLeader;

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public String getSubDeptName() {
        return subDeptName;
    }

    public void setSubDeptName(String subDeptName) {
        this.subDeptName = subDeptName;
    }

    public String getLevelName() {
        return levelName;
    }

    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    public Date getNowTime() {
        return nowTime;
    }

    public void setNowTime(Date nowTime) {
        this.nowTime = nowTime;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getIsLeader() {
        return isLeader;
    }

    public void setIsLeader(Integer isLeader) {
        this.isLeader = isLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.pid
     *
     * @return the value of tbl_gb_task_info.pid
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.pid
     *
     * @param pid the value for tbl_gb_task_info.pid
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.task_des
     *
     * @return the value of tbl_gb_task_info.task_des
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public String getTaskDes() {
        return taskDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.task_des
     *
     * @param taskDes the value for tbl_gb_task_info.task_des
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setTaskDes(String taskDes) {
        this.taskDes = taskDes == null ? null : taskDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.initiator
     *
     * @return the value of tbl_gb_task_info.initiator
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Long getInitiator() {
        return initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.initiator
     *
     * @param initiator the value for tbl_gb_task_info.initiator
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setInitiator(Long initiator) {
        this.initiator = initiator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.end_date
     *
     * @return the value of tbl_gb_task_info.end_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.end_date
     *
     * @param endDate the value for tbl_gb_task_info.end_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.actual_end_date
     *
     * @return the value of tbl_gb_task_info.actual_end_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Date getActualEndDate() {
        return actualEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.actual_end_date
     *
     * @param actualEndDate the value for tbl_gb_task_info.actual_end_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setActualEndDate(Date actualEndDate) {
        this.actualEndDate = actualEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.deptId
     *
     * @return the value of tbl_gb_task_info.deptId
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.deptId
     *
     * @param deptid the value for tbl_gb_task_info.deptId
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.status
     *
     * @return the value of tbl_gb_task_info.status
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.status
     *
     * @param status the value for tbl_gb_task_info.status
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.source
     *
     * @return the value of tbl_gb_task_info.source
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.source
     *
     * @param source the value for tbl_gb_task_info.source
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.level
     *
     * @return the value of tbl_gb_task_info.level
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Long getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.level
     *
     * @param level the value for tbl_gb_task_info.level
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setLevel(Long level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.note
     *
     * @return the value of tbl_gb_task_info.note
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.note
     *
     * @param note the value for tbl_gb_task_info.note
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.first_date
     *
     * @return the value of tbl_gb_task_info.first_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Integer getFirstDate() {
        return firstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.first_date
     *
     * @param firstDate the value for tbl_gb_task_info.first_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setFirstDate(Integer firstDate) {
        this.firstDate = firstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.over_date
     *
     * @return the value of tbl_gb_task_info.over_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Integer getOverDate() {
        return overDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.over_date
     *
     * @param overDate the value for tbl_gb_task_info.over_date
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setOverDate(Integer overDate) {
        this.overDate = overDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.create_time
     *
     * @return the value of tbl_gb_task_info.create_time
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.create_time
     *
     * @param createTime the value for tbl_gb_task_info.create_time
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_gb_task_info.p_id
     *
     * @return the value of tbl_gb_task_info.p_id
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public Long getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_gb_task_info.p_id
     *
     * @param pId the value for tbl_gb_task_info.p_id
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    public void setpId(Long pId) {
        this.pId = pId;
    }
}