package com.xwkj.ygjces.Mapper.auto;

import com.xwkj.ygjces.model.ApproverLog;
import org.springframework.stereotype.Repository;

@Repository
public interface ApproverLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_task_approver_log
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_task_approver_log
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    int insert(ApproverLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_task_approver_log
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    int insertSelective(ApproverLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_task_approver_log
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    ApproverLog selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_task_approver_log
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    int updateByPrimaryKeySelective(ApproverLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_task_approver_log
     *
     * @mbggenerated Thu Aug 29 13:40:30 CST 2019
     */
    int updateByPrimaryKey(ApproverLog record);
}