package com.xwkj.ygjces.Mapper.auto;

import com.xwkj.ygjces.model.OrganizationInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Repository
public interface OrganizationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_organization_info
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_organization_info
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    int insert(OrganizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_organization_info
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    int insertSelective(OrganizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_organization_info
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    OrganizationInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_organization_info
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    int updateByPrimaryKeySelective(OrganizationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_organization_info
     *
     * @mbggenerated Tue Jul 09 22:33:55 CST 2019
     */
    int updateByPrimaryKey(OrganizationInfo record);
}