package com.xwkj.ygjces.Mapper.auto;

import com.xwkj.ygjces.model.OvertimeModel;
import org.springframework.stereotype.Repository;

@Repository
public interface OvertimeModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_overtime
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_overtime
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    int insert(OvertimeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_overtime
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    int insertSelective(OvertimeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_overtime
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    OvertimeModel selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_overtime
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    int updateByPrimaryKeySelective(OvertimeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_overtime
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    int updateByPrimaryKey(OvertimeModel record);
}