package com.xwkj.ygjces.Mapper.auto;

import com.xwkj.ygjces.model.RemindModel;
import org.springframework.stereotype.Repository;

@Repository
public interface RemindModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_remind
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_remind
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    int insert(RemindModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_remind
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    int insertSelective(RemindModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_remind
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    RemindModel selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_remind
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    int updateByPrimaryKeySelective(RemindModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_xm_remind
     *
     * @mbggenerated Tue Aug 27 10:21:37 CST 2019
     */
    int updateByPrimaryKey(RemindModel record);
}