package com.xwkj.ygjces.Mapper.auto;

import com.xwkj.ygjces.model.TaskInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface TaskInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_info
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_info
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int insert(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_info
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int insertSelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_info
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    TaskInfo selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_info
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int updateByPrimaryKeySelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_info
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int updateByPrimaryKey(TaskInfo record);
}