package com.xwkj.ygjces.Mapper.auto;

import com.xwkj.ygjces.model.TaskRemind;
import org.springframework.stereotype.Repository;

@Repository
public interface TaskRemindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_remind
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_remind
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int insert(TaskRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_remind
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int insertSelective(TaskRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_remind
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    TaskRemind selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_remind
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int updateByPrimaryKeySelective(TaskRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_remind
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int updateByPrimaryKey(TaskRemind record);
}