package com.xwkj.ygjces.Mapper.auto;

import com.xwkj.ygjces.model.TaskOverTime;
import org.springframework.stereotype.Repository;

@Repository
public interface TaskOverTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_overtime
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_overtime
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int insert(TaskOverTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_overtime
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int insertSelective(TaskOverTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_overtime
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    TaskOverTime selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_overtime
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int updateByPrimaryKeySelective(TaskOverTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_overtime
     *
     * @mbggenerated Wed Sep 18 17:19:24 CST 2019
     */
    int updateByPrimaryKey(TaskOverTime record);
}