package com.xwkj.ygjces.Mapper.auto;

import com.xwkj.ygjces.model.TaskInfoNotice;
import org.springframework.stereotype.Repository;

@Repository
public interface TaskInfoNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_notice
     *
     * @mbggenerated Sat Jan 11 17:21:55 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_notice
     *
     * @mbggenerated Sat Jan 11 17:21:55 CST 2020
     */
    int insert(TaskInfoNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_notice
     *
     * @mbggenerated Sat Jan 11 17:21:55 CST 2020
     */
    int insertSelective(TaskInfoNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_notice
     *
     * @mbggenerated Sat Jan 11 17:21:55 CST 2020
     */
    TaskInfoNotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_notice
     *
     * @mbggenerated Sat Jan 11 17:21:55 CST 2020
     */
    int updateByPrimaryKeySelective(TaskInfoNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_gb_task_notice
     *
     * @mbggenerated Sat Jan 11 17:21:55 CST 2020
     */
    int updateByPrimaryKey(TaskInfoNotice record);
}